# Generated by Django 2.0.1 on 2018-03-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=100)),
                ('booked_seats', models.CharField(max_length=250)),
                ('count', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('txnid', models.CharField(default='', max_length=75)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('coupon_code', models.CharField(max_length=5)),
                ('discount_percent', models.IntegerField(default=0)),
                ('is_activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_type', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('total_seats', models.IntegerField(default=0)),
                ('left_seats', models.IntegerField(default=0)),
                ('booked_seats', models.CharField(blank=True, max_length=2000)),
                ('cover_logo', models.FileField(upload_to='')),
                ('eventdate', models.DateField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='coupon',
            name='event',
            field=models.ForeignKey(on_delete=None, to='events.Events'),
        ),
        migrations.AddField(
            model_name='bookdetails',
            name='event',
            field=models.ForeignKey(on_delete=None, to='events.Events'),
        ),
    ]
